### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Ian-Stewart-Binks/Foosball#16]
Travis or Jenkins? OpenShift has support for Jenkins, but I haven't been able to sign in...

**Comment by Anirudh94** [comment]
Doesn't matter too much either way, but Travis is easier to set up and has native github pull request workflow (i.e. checks build for PRs). Also it looks nicer :)

**Comment by Ian-Stewart-Binks** [comment]
+1 for Travis. @emmettu ?

**Comment by emmettu** [comment]
@Ian-Stewart-Binks :+1:

**Comment by Ian-Stewart-Binks** [comment]
@Anirudh94 Do you want to set this up?

**Comment by Anirudh94** [comment]
@Ian-Stewart-Binks Sure :D

**Comment by Ian-Stewart-Binks** [comment]
@Anirudh94 Can you add a badge to the README as well?

**Comment by Ian-Stewart-Binks** [comment]
Good Job @Anirudh94!
