### ISSUE TITLE
Fork official foosball rules

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Ian-Stewart-Binks/Foosball#20]
We should fork these rules: http://www.foosball.com/learn/rules/ustsa/

**Comment by Ian-Stewart-Binks** [comment]
Foosball rules should also live somewhere that isn't an HTML page.

**Comment by Ian-Stewart-Binks** [comment]
@emmettu How's this going?

**Comment by emmettu** [comment]
BeautifulSoup doesn't parse it correctly. There are duplicate tags because some of the html is malformed. However, the the abridged list would be pretty easy to parse so I'm going to push that soon. People can build off of it they see a way of parsing the larger list.

**Comment by Ian-Stewart-Binks** [comment]
That's unfortunate to hear about BeautifulSoup, but I suppose it's what we expected when we first looked at the source. I'm good with parsing the abridged version. Perhaps we could get in contact with the website maintainers, and provide them with a valid html doc.

In any case, thanks for keeping us posted.

**Comment by Ian-Stewart-Binks** [comment]
Fixed by #30
